- client/changes/bug_6797_add-dependency-on-twisted
- client/pkg/requirements.pip
- client/src/leap/soledad/client/events.py
- common/pkg/requirements.pip
- common/setup.py
- common/src/leap/soledad/common/__init__.py
- server/changes/bug_6797_add-dependency-on-twisted
- server/pkg/requirements.pip
This pull request handles many dependency issues:
* twisted
* oauth
* leap.common
It also includes a fix in common's setup.py to ensure all tests are excluded from installation and as a consequence also from debian package.
> Bug/6797 add dependency on twisted (and fix/improve others)

- scripts/db_access/client_side_db.py
- scripts/db_access/util.py
With changes in soledad client api to make it async, the supporting scripts
also have to be updated. This commit also adds more functionalities as
exporting incoming mail and public or private keys.
> [fix] turn client side db access script into async

- common/changes/bug_6833_remove-unneeded-params-from-couch-server-state
- common/src/leap/soledad/common/couch.py
- server/changes/bug_6833_remove-unneeded-params-from-couch-server-state
- server/src/leap/soledad/server/__init__.py
This commit removes some leftover code from a time when Soledad Server used to
check for permissions on certain databases when starting (i.e. shared and
tokens databases). This was later removed as correct permissions enforcement
was relayed to tapicero.
Closes: #6833.
> [fix] remove unneded params to CouchServerState

- debian/control
This commit also does the following in the debian/control file:
* Add dh-python package build dependency.
* Remove trailing whitespace after new-line dot markers on package
descriptions. This was causing a lintian warning saying
description-contains-invalid-control-statement.
> [pkg] bump client/server dependencies on common

- server/pkg/requirements.pip
soledad-common versions before 0.6.5 do not contain the fix for #6833 and thus
will not work with most recent server. That is why we have to bump this
soledad-server dependency on soledad.common.
> [pkg] bump version of server dependency on common

- client/changes/feat-refactor_decr_pool
- client/src/leap/soledad/client/encdecpool.py
- client/src/leap/soledad/client/http_target.py
It makes the code simpler and clearer to use a deferred instead of
having to pull on 'has_finished'.
- Related: #7234
> [refactor] use a deferred to signal when SyncDecriptionPool has finished

- client/pkg/requirements-leap.pip
- client/pkg/requirements.pip
- client/pkg/utils.py
- client/setup.py
- common/pkg/requirements-leap.pip
- common/pkg/requirements.pip
- common/pkg/utils.py
- common/setup.py
- server/pkg/requirements-leap.pip
- server/pkg/requirements.pip
- server/pkg/utils.py
- server/setup.py
this is part of a process to make the setup of the development mode less
troublesome. from now on, setting up a virtualenv in pure development
mode will be as easy as telling pip to just install the external dependencies::
pip install -r pkg/requirements.pip
and traversing all the leap repos for the needed leap dependencies doing::
python setup.py develop
- Related: #7288
> [pkg] separate leap requirements

- .gitignore
- client/pkg/requirements-latest.pip
- client/src/leap/soledad/client/api.py
- common/pkg/requirements-latest.pip
- common/src/leap/soledad/common/tests/util.py
- server/pkg/requirements-latest.pip
The changes include:
- Tests are now running again after the change to zmq, the soledad tests would not run because the zmq_init would fail with certificate error. I disabled events for the soledad tests so we won't have that problem anymore.
You can take a look here: https://snap-ci.com/pixelated-project/soledad/branch/develop/logs/defaultPipeline/22/Tests?back_to=build_history
- Also added some leftovers files from the tests to the gitignore
- Created a requirements-latest.pip to be able to run soledad from head without depending on pypi or specific versions of leap libraries
> Soledad tests are running again

- client/src/leap/soledad/client/api.py
before sqlcipher backend, or the attribute is not found.
this is a leftover of the recent refactor
> [bug] Soledad._crypto has to be initialized earlier

- common/setup.cfg
when copying a generic config file over in previous commit
> [tests] re-add accidental removal

- debian/control
lintian complains about the spaces on empty lines.
E: soledad-client: description-contains-invalid-control-statement
N:    The description contains a line starting with a dot (.). This is not
N:    allowed.
N:    Refer to Debian Policy Manual section 5.6.13 (Description) for details.
N:    Severity: serious, Certainty: certain
N:    Check: description, Type: binary, udeb
> [style] fix lintian

- debian/pydist-overrides
dh_python guesses that leap.common is provided by the debian
package 'python-leap.common' but it is in 'python-leap-common'
> map the leap.common package to the correct debian package

- client/src/leap/soledad/client/api.py
- client/src/leap/soledad/client/http_target.py
- common/src/leap/soledad/common/tests/test_sqlcipher_sync.py
- common/src/leap/soledad/common/tests/test_sync.py
- common/src/leap/soledad/common/tests/test_sync_target.py
Fixed the parser tests on http target after the changes, one exception was being expected but didn't exist so I fixed that in the code too.
The last commit from Leap left a Pep8 warning, that was fixed in the last commit here
> Fixed http target sync tests

- client/pkg/pip_install_requirements.sh
- common/pkg/pip_install_requirements.sh
- server/pkg/pip_install_requirements.sh
--use-leap-wheels sets --trusted-host (remove it when we have a proper
cert) and WHEELHOUSE to https://ftp.lizard.leap.se
Until we get ftp.lizard cname, use lizard as the wheels server.
- Related: #7339
> [feat] WHEELHOUSE can be a url + --use-leap-wheels

- .gitignore
- scripts/profiling/memdebug.py
- scripts/profiling/sync/profile-sync.py
- scripts/profiling/sync/run_plop_server.sh
- scripts/profiling/util.py
Updating the profile-sync script to the latest deferred-based sync.
- Added a couple of options to have finer control about what output to
get.
- Add support for the plop profiler https://pypi.python.org/pypi/plop/
- To get meaningful plop profiles, make sure to disable the system stats
collection, like this::
./profile-sync.py --no-stats --plop -b /tmp/syncdata/ -p sikret user@provider
A good practice for this is having a pre-seeded soledad account
(currently you have to do that through the wizard, a cli will be very
nice to have in the coming future) with a known amount of data (for
instance, sending some mails with known payload weight).
It is VERY IMPORTANT that you *NEVER* process the data in this account
(ie, do not ever log in with a mail client, for instance, since that
will alter …
> [feat] update profile-sync script, add plop profiling

- client/src/leap/soledad/client/adbapi.py
Code is trying to close a closed threadpool. This raises errors with Twisted 15.4.
> [bug] check threadpool state before closing it

- client/src/leap/soledad/client/encdecpool.py
- client/src/leap/soledad/client/http_target/api.py
- client/src/leap/soledad/client/sqlcipher.py
- common/src/leap/soledad/common/tests/util.py
We are getting "too many files open" while running tests with 1024 max
files open. This is a leak from close methods. Some of them should be fixed
on this commit, but further investigation may be necessary.
> [bug] review some of the close methods

- client/changes/bug_set-active-secret
- client/src/leap/soledad/client/secrets.py
- bug: we were dumping the received secrets locally to disk *before*
setting the received property for the active secret, and therefore the
'active_secret' was always marked as null.
- refactor common code into an utility method.
> [bug] set the received active secret before saving local file

- server/changes/create_db_cmd
- server/pkg/create-user-db
- server/src/leap/soledad/server/__init__.py
netrc file was hardcoded inside create-user-db. Now it reads the path
from /etc/leap/soledad-server.conf as done on server process.
The new configuration property is called 'admin_netrc'.
> [feat] read netrc path from configuration file

- client/src/leap/soledad/client/http_target/__init__.py
this is a workaroud to reduce the chances of failed sync due to
timeouts. this should be properly tackled by:
1. implementing proper cancellable for the sync operation.
2. implementing a retry count at the level of a single request, handled
internally by soledad.
in this way we can remove the retries logic from the soledadbootstrapper
in the bitmask client.
- Related: #7382
> [bug] increase http request timeout time to 90s

- common/src/leap/soledad/common/couch.py
- common/src/leap/soledad/common/tests/test_couch.py
- server/pkg/requirements.pip
Wheezy has python-couchdb at 0.8 and beaker at 1.6.3.
This version wasn't pinned, making virtualenv install 1.0 and 1.7.0.
Those new versions deliver better api, but aren't supported on wheezy.
This PR pins versions for wheezy and fixes necessary code.
> [bug] pin libraries and fixes to wheezy

- client/changes/bug_missing_design_doc_handler
- client/src/leap/soledad/client/sync.py
MissingDesignDocError raised on get_sync_info due to a missing design
document will be handled by the server during sync.
Ensure is now False by default, and thus database creation can deliver
an empty one that will be ensured during sync, following the ensure
parameter.
> [bug] handle MissingDesignDocError after get_sync_info

- server/src/leap/soledad/server/sync.py
It was 3600s, but closing connections seems to yet depend on garbage
collection and now causes server to leak file handlers. 120s should be
enough to a sync session finish. Also, lowering this value will only
make very long syncs poke couch every 2 minutes, while raising
this value will keep memory busy for useless time.
I couldn't find a proper place to call close on the session, but I will keep in mind that maybe, in the future, 'session' on CouchDB should be something shared to reuse connections instead of creating more.
> [bug] reduce overall sync session caching to 120s in order to prevent file handlers leak

- common/src/leap/soledad/common/couch.py
- common/src/leap/soledad/common/tests/fixture_soledad.conf
- common/src/leap/soledad/common/tests/test_couch.py
- common/src/leap/soledad/common/tests/test_server.py
- server/changes/feat_configurable_ensure
- server/pkg/create-user-db
- server/src/leap/soledad/server/__init__.py
LEAP Platform needs to granularly allow access on user database for
other services, like mx. This is now possible by editing
soledad-server.conf file. A new section 'database-security' was added
and it is parsed during 'create-user-db' to be set on security design
document, present on every per-user database.
> [feat] read security doc from configuration

- client/src/leap/soledad/client/sync.py
- common/changes/next-changelog.rst
- common/src/leap/soledad/common/couch/errors.py
- common/src/leap/soledad/common/errors.py
by subclassing the MissingDesignDocError, we don't have to import the
soledad.common.couch submodule into the soledad.client.sync
- Resolves: #7626
> [bug] fix indirect dependency on couchdb for client

- common/src/leap/soledad/common/couch/__init__.py
- common/src/leap/soledad/common/couch/support.py
- common/src/leap/soledad/common/errors.py
Current code was tested on couch 1.6 and a monkeypatch got removed
during refactor. This commit re-adds it, but in a separate module that
is intended to hold temporary code for compatibility that can be removed
on version upgrades.
----
Sorry for removing that.
Pixelated is using couchdb 1.6 and I have this installed on my machine as well. Luck of ours that snap has an older couchdb and broke the build.
> [bug] put a monkeypatch back for bigcouch

- client/src/leap/soledad/client/encdecpool.py
- common/src/leap/soledad/common/backend.py
- common/src/leap/soledad/common/tests/test_encdecpool.py
This info can be changed by another syncing replica and would not
reflect real database generation. That would be ok inside of the same
sync, but can cause trouble on concurrent syncs.
The other calls are ok, since they hold info that doesnt change during
concurrent syncs or are only read/write by the replica syncing. A global
cache could fit better this removed case, but for now let's stay on the
safe side.
> [bug] generation_info cant be cached per replica

- server/src/leap/soledad/server/__init__.py
While parsing the configuration file, if a key doesn't exists we need to
skip it.
> [bug] skip missing keys on existing sections

- common/src/leap/soledad/common/tests/test_soledad.py
That event was triggering with the user uuid instead
of the user_data, adapted that to conform with the rest
of the events
> [bug] updated SOLEDAD_DONE_DOWNLOADING_KEYS trigger

- common/src/leap/soledad/common/couch/__init__.py
database_security parameter was either undocumented or incomplete. This
commit adds a few more doc to make it consistent with latest changes.
Closes #7689
> [docs] incomplete doc for security config parameter

- client/src/leap/soledad/client/encdecpool.py
- common/src/leap/soledad/common/tests/test_sync_deferred.py
The sequential handling of downloading and inserting docs blocked the twisted event loop (see the _process_decrypted_docs in the diff below)
```python
for doc_fields in insertable:
self._insert_decrypted_local_doc(*doc_fields)
```
Move the insertion into a background thread to keep the event loop free and able to handle the download requests
> Fix sync timeout

- client/changes/feat_use_cryptography
- client/pkg/requirements.pip
- client/src/leap/soledad/client/crypto.py
cryptography comes from OpenSSL and Twisted dependencies, so it's
already installed.
This commit removes a compiled dependency, also possibly making it
easier to use on Windows.
> [feat] use cryptography instead of pycryptopp

- client/src/leap/soledad/client/crypto.py
- client/src/leap/soledad/client/encdecpool.py
Do not initialize the openssl context on each call to decrypt.
I'm not 100% sure of the causal chain, but it seems that the
initialization of the osrandom engine that openssl backend does might be
breaking havoc when sqlcipher is calling rand_bytes concurrently.
further testing is needed to confirm this is the ultimate cause, but in
my tests this change avoids the occurrence of the dreaded Floating Point
Exception in soledad/sqlcipher.
- Resolves: #8180
> [bug] initialize OpenSSL context just once

- client/src/leap/soledad/client/sqlcipher.py
We discovered that class was registering a `finalClose` to be
executed on reactor shutdown.
On the multiuser scenario, a logout destroys Soledad and should
properly terminate everything related to it. That SQLCipherU1DBSync
instance was being held even after logout by the reactor so it
could call that `finalClose` on shutdown.
The `finalClose` only set running to False and set a `shutdownID` that
was not used anywhere else, so we removed it and moved setting
running to False to the `close` function method. That way we preserve
the functionality but let the instance be properly garbage collected
on logout.
> [Memory Leak] Removed finalClose from SQLCipherU1DBSync
